### PR TITLE
Add English thesaurus

### PR DESCRIPTION
**Pull request by lulu-berlin**
I think it would make sense to include the openoffice English thesaurus too, because the normal English thesaurus used in VIM has too many entries per word which makes it difficult to use.

### CODE REVIEW

**Comment by grepsuzette** [comment]
Hey, @yever 
thank you. I was thinking the same but not having the english one for OpenOffice I was delaying this. 
I merged your commit. You might want to regenerate one thesaurus at some point, I added very basic support for multi-word synonyms (using _ as a separator). See the small changes in the script.

**Comment by lulu-berlin** [comment]
Hi @emugel :smile: 
The lack of thesaurus files for VIM is frustrating, so I was glad to find your project.

Regarding the space vs. underscore issue: in writing prose, it is possible to use `:set iskeyword+=32` and get multi-word synonyms not broken into separate words. this still doesn't help with getting a synonym for a multi-word...
The underscore solution is OK, but it is still quite annoying to have to add them and then to erase them from the chosen synonym. I wonder if there's a way to script it.
For the time being I'll add thesaurus files with underscores.

BTW, I read that the OpenOffice thesaurus files are actually derived from [WordNet](https://wordnet.princeton.edu/). I think it would be nice to try to make a script to create thesaurus files directly from there.

**Comment by grepsuzette** [comment]
Hum I guess 32 is the code for the space character. 
That's very interesting.
In this case we'd better keep the underscore for indexed words, and getting rid of them in the list of synonyms, and simply add a notice in README. 

I'll check the WordNet to see what can be get from there. Thanks for those precious info!

**Comment by lulu-berlin** [comment]
You're very welcome. 

I read about adding the space to `iskeyword` and people tend to discourage it ([here](http://stackoverflow.com/questions/21127951/is-it-allowed-to-include-a-space-in-vims-iskeyword-option), for example), even though the only side-effect I found for it is that it makes a search like `/\k` ignore spaces, but not `/\w`, `w`, `*`, and other things that have to do with words.

Be it as it may, I have created a script that inserts underscores if a multi-word term is found in the thesaurus (within a 6-word window), and removes them once a synonym is chosen. Here is the [gist](https://gist.github.com/yever/27a03627e07fd403fd87). I'll make a pull-request for it.

**Pull request merged**
